import PDFDocument from "pdfkit";

const generatePdf = async (data) => {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      size: "A4",
      margin: 50,
      info: {
        Author: "Tejas Ai",
        Title: data.title || "Document",
        Creator: "Tejas Ai",
      },
    });

    const chunks = [];

    doc.on("data", (chunk) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", (err) => reject(err));

    // Title
    doc
      .fillColor("#111827")
      .fontSize(28)
      .text(data.title || "Untitled Document", {
        align: "center",
      });

    // Subtitle
    if (data.subtitle) {
      doc.moveDown(0.5);

      doc.fillColor("#6B7280").fontSize(12).text(data.subtitle, {
        align: "center",
      });

      doc.moveDown(2);
    }

    // Sections
    data.sections?.forEach((section) => {
      // Heading
      doc.fillColor("#111827").fontSize(18).text(section.heading);

      doc.moveDown(0.5);

      // Points
      section.points?.forEach((point) => {
        doc.fillColor("#374151").fontSize(12).text(`• ${point}`, {
          lineGap: 5,
        });
      });

      doc.moveDown();
    });

    // Footer

    doc.moveDown(2);

    doc.fillColor("#9CA3AF").fontSize(10).text("Generated by Tejas AI", {
      align: "center",
    });

    doc.end();
  });
};

export default generatePdf;
